#!/bin/sh
set -e

PROGRAM=/usr/sbin/seunshare

if [ "$1" = configure ]; then
    if which setcap > /dev/null && [ -e $PROGRAM ]; then
        if ! setcap cap_setpcap,cap_setuid,cap_fowner,cap_dac_override,cap_sys_admin,cap_sys_nice=pe $PROGRAM >/dev/null 2>&1; then
            echo "Setting capabilities for seunshare using Linux Capabilities failed, falling back to setuid."
            chmod 4755 $PROGRAM
        fi
    fi
fi

#DEBHELPER#

exit 0
