etc/dbus-1/system.d/org.selinux.conf
#usr/bin/system-config-selinux
usr/lib/python*/*-packages/sepolicy/gui.py
usr/lib/python*/*-packages/sepolicy/help/*.png usr/share/sepolicy/help/
usr/lib/python*/*-packages/sepolicy/help/*.txt usr/share/sepolicy/help/
usr/lib/python*/*-packages/sepolicy/sedbus.py
usr/lib/python*/*-packages/sepolicy/sepolicy.glade usr/share/sepolicy/
usr/share/dbus-1/system-services/org.selinux.service
usr/share/icons/hicolor/*/apps/sepolicy.png
#usr/share/icons/hicolor/24x24/apps/system-config-selinux.png
#usr/share/man/man8/selinux-polgengui.8*
usr/share/man/man8/sepolicy-gui.8*
#usr/share/man/man8/system-config-selinux.8*
usr/share/pixmaps/sepolicy.png
#usr/share/pixmaps/system-config-selinux.png
#usr/share/polkit-1/actions/org.selinux.config.policy
usr/share/polkit-1/actions/org.selinux.policy
#usr/share/system-config-selinux/*.glade
usr/share/system-config-selinux/*.py
#usr/share/system-config-selinux/selinux-polgengui.desktop usr/share/applications/
usr/share/system-config-selinux/sepolicy.desktop usr/share/applications/
#usr/share/system-config-selinux/system-config-selinux.desktop usr/share/applications/
#usr/share/system-config-selinux/system-config-selinux.png
